version: "3"

services:
  postgres:
    image: postgres:9.6
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
  - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        "5432:5432"

